//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillionBokeh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Organiser { get; set; }
        public short Duration { get; set; }
        public decimal Fee { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
